events {}
http {
    server {
        listen 80;

        proxy_set_header Connection '';
        proxy_http_version 1.1;
        chunked_transfer_encoding off;
        proxy_buffering off;
        proxy_cache off;

        location /sse {
            proxy_pass http://mcp-pdf-reader:8000/sse;
        }
        location /messages {
            proxy_pass http://mcp-pdf-reader:8000/messages;
        }


        location /fs/ {
            proxy_pass http://mcp-filesystem:8001;
        }

        location /web/ {
            proxy_pass http://mcp-playwright:8002;
        }
    }
}