events {}
http {
    server {
        listen 80;

        # Configuración VITAL para que Server-Sent Events (SSE) no se corte
        proxy_set_header Connection '';
        proxy_http_version 1.1;
        chunked_transfer_encoding off;
        proxy_buffering off;
        proxy_cache off;

        # 1. Rutas del PDF Reader (Lo dejamos en la ruta raíz para no tocar el código de Python)
        location /sse {
            proxy_pass http://mcp-pdf-reader:8000/sse;
        }
        location /messages {
            proxy_pass http://mcp-pdf-reader:8000/messages;
        }

        # 2. Rutas del Filesystem
        location /fs/ {
            proxy_pass http://mcp-filesystem:8001;
        }

        # 3. Rutas de Playwright
        location /web/ {
            proxy_pass http://mcp-playwright:8002;
        }
    }
}